[package]
name = "lox-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
anyhow = "1.0.44"
log = "0.4.14"
env_logger = "0.9.0"
itertools = "0.10.1"
